### PR TITLE
feat: added trick count and icons

### LINKED ISSUE #9: Add Trick Counter to each person's avatar on table, and to their Card.

### PR DESCRIPTION
**Pull request by wmichaelshirk**
I also snuck in the game-length options, waiting to be wired up. Do you think we need others?

### CODE REVIEW

**Review by DoctorWitty — CHANGES_REQUESTED** [review]
This all looks good to me, although could you not also add the trick value on the table pretty easily as well? Feel like that would just be a couple more lines, but maybe you haven't done it for a good reason?

**Comment by wmichaelshirk** [comment]
> This all looks good to me, although could you not also add the trick value on the table pretty easily as well? Feel like that would just be a couple more lines, but maybe you haven't done it for a good reason?

Ok - added that in as well (and also highlighted the active player) if you'd like to reapprove. :-)

**Review by DoctorWitty — CHANGES_REQUESTED** [review]
Sorry to send it back again, but the only issue I have is that the card played by the player in North covers their trick count on the table. I suppose it doesn't matter as it's in the player tables but it's probably better if it's shown. What do you think? Probably just need to slightly increase the height of the table and make sure everything else is still aligned.

**Comment by wmichaelshirk** [comment]
Such a taskmaster! :laughing: I moved them all from "the bottom" to "the right of the player" all the way around. See if that looks better to you.

**Review by DoctorWitty — APPROVED** [review]
I think we could maybe still jiggle these around a bit, but I'm approving it because there's no issues and I don't want to be any more annoying haha!
We should get all of the logic stuff sorted out and come back to design near the end.

**Comment by DoctorWitty** [comment]
Oh, you also had duplicated game options so I deleted the duplicated ones. You can check that before you merge if you want.

**Pull request merged**
